package com.cj.dataSynchronization.func.modular.tth.dtos;

import lombok.Data;

import java.io.Serializable;

@Data
public class QueryRealTimeDataDto implements Serializable {
    private String SP_URL;
    private String DEPT_ID;
    private Double SQ_WATER;
    private String DEPT_ID_NAME;
    private String BEGIN_TIME_MARK;
    private String GD_PIPE_PRESSURE;
    private String QX_SOIL_DATA;
    private String SQ_INPUT_FLOW;
    private Double GD_MONITOR_FLOW;
    private String QX_EVAPORATION;
    private String DATA_ID;
    private String ID;
    private String YQ_RAIN_FALL_12;
    private String AVG_INPUT_FLOW;
    private Double WATER_DAILY;
    private Double GD_MONITOR_FLOW_RATE;
    private String OVERTIME_SET;
    private String WARN_NOTE;
    private String SQ_GATE_OPEN_HOLES;
    private String QX_TEMPERATURE;
    private String SP_CHANNEL_NO;
    private String MONITOR_TYPE;
    private String SHQ_SOIL_HUM_DATA;
    private String YQ_RAIN_FALL_1;
    private String WARN_COLOR;
    private String SP_PORT;
    private String QX_RAIN_FALL;
    private String YQ_RAIN_FALL_3;
    private String QX_SOLAR_RADIATION;
    private Double YESTERDAY_AVG_FLOW;
    private String YQ_RAIN_FALL_6;
    private String MONITOR_NAME;
    private String PICTURE_PATH;
    private String AVG_CAPACITY;
    private String YQ_RAIN_FALL_24;
    private Double SQ_TOTAL_FLOW;
    private String GD_IS_NULL_PIPE;
    private String QX_WIND_SPEED;
    private String DXS_BURIAL_DEPTH;
    private String DXS_WATER;
    private Double SQ_MONITOR_FLOW;
    private Double AVG_WATER_DEEP;
    private String SQ_P_TOTAL_FLOW;
    private String QX_WIND_POWER;
    private Double AVG_WATER_LEVEL;
    private String QX_PRESSURE;
    private Double SQ_MONITOR_FLOW_RATE;
    private String IS_WATER_LEVEL;
    private String SQ_N_TOTAL_FLOW;
    private String MONITOR_DATA;
    private String BUILD_ID;
    private String BEGIN_TIME;
    private String SHQ_SOIL_DATA;
    private String MEASURE_TYPE;
    private Double YESTERDAY_WATER_DAILY;
    private String DXS_WATER_LEVEL;
    private String MONITOR_TIME;
    private String GD_N_TOTAL_FLOW;
    private String SHQ_SOIL_TEM_DATA;
    private Double SQ_WATER_LEVEL;
    private Double VOLTAGE;
    private String SQ_DOWN_LEVEL;
    private String LOCATION_TYPE;
    private Double SQ_CAPACITY;
    private String SELF_CODE;
    private String QX_DIRECTION;
    private String WARN_STATE;
    private String SQ_GATE_HEIGHT;
    private String GD_P_TOTAL_FLOW;
    private Double AVG_FLOW;
    private Double YEAR_WATER_DAILY;
    private String REGION_ID;
    private String LOCATION_ID;
    private String MONITOR_WAY;
    private String SP_V_PASSWORD;
    private String SP_V_USER_ID;
    private String SQ_DOWN_WATER;
    private String QX_HUMIDITY;
    private Double GD_TOTAL_FLOW;
    private String WARN_TYPE;
    private OperateTimeDto OPERATE_TIME;
}
